### ISSUE TITLE
graphics-mode output in /etc/default/grub

### ISSUE THREAD

**Issue by reputet** [shvchk/fallout-grub-theme#1]
The script Installation was succeeded, but the theme wasn't applied.

Since I had a line
`GRUB_TERMINAL_OUTPUT="console"`
in the file **/etc/default/grub**, my grub menu was in a text mode as well.

Therefore, the variable **GRUB_TERMINAL_OUTPUT** must be set in one of graphics modes e.g. **gfxterm** or **vga_text**.
Otherwise grub won't be loaded in the graphics-mode and won't use any of themes although it is defined in the **/etc/default/grub**

*/etc/default/grub* documentation:
https://www.gnu.org/software/grub/manual/grub/html_node/Simple-configuration.html

**Comment by shvchk** [comment]
Graphical output is default almost everywhere I think, probably you have changed that setting. I could make install script comment it if it's not commented, what do you think?

**Comment by reputet** [comment]
> Graphical output is default almost everywhere I think

I don't know why my settings were different.
Maybe you're right and I've changed it.

>  I could make install script comment it if it's not commented, what do you think?

I think it's a good idea.
[As far as I can see ](https://askubuntu.com/a/509925), the line `GRUB_TERMINAL_OUTPUT=console` (or `GRUB_TERMINAL=console` what is basically the same) is commented by default, so it's likely to work.

**Comment by shvchk** [comment]
Sorry, forgot about this. Should be fixed with d9c6f2d

**Comment by mehrad77** [comment]
I commented it but it's still not working
