### ISSUE TITLE
Mention unzip dependency

### ISSUE THREAD

**Issue by hubmartin** [shvchk/fallout-grub-theme#11]
Hi, thanks for awesome theme.
I had small issue that theme was not working properly. After second install I saw that the unzip command was not installed on my ubuntu server. I would suggest to add it to install script, docs or use other command that is already installed in the system?
https://twitter.com/hubmartin/status/1458553733747515393

**Comment by shvchk** [comment]
Fixed in 6fb2bbd, thanks!
