### ISSUE TITLE
[bug] ID_LIKE is unbound

### ISSUE THREAD

**Issue by Freed-Wu** [shvchk/fallout-grub-theme#12]
When I run `./install.sh`, it will

```
./install.sh: line 85: ID_LIKE: unbound variable
```

I notice after `source /etc/os-release`, it will
```
    if [[ "$ID" =~ (debian|ubuntu|solus) || \
          "$ID_LIKE" =~ (debian|ubuntu) ]]; then
```

However, `/etc/os-release` in arch now is

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

No ID_LIKE.

And `install.sh` don't have executable mode. I must `chmod +x install.sh` after `git clone`.
I suggest to add executable mode.

Thanks.

**Comment by shvchk** [comment]
Thanks, @Freed-Wu! I think I've fixed this, please test :wink:

**Comment by shvchk** [comment]
@Freed-Wu if you've tried updated version, please let me know if it works well, so I can port this fix to my other themes.

**Comment by Freed-Wu** [comment]
It's great!
