### ISSUE TITLE
Windows Entry does not have an icon

### ISSUE THREAD

**Issue by dillasyx** [shvchk/fallout-grub-theme#2]
The installation worked quite fine, and the arch entry hast the correct icon, but the windows entry does not have any

**Comment by shvchk** [comment]
The theme has windows icon, so it seems your system has a problem with identifying/labeling Windows entry as Windows :smile:

Icon is selected by GRUB based on the *classes* specified for the menu entry in `/boot/grub/grub.cfg` (see [GRUB docs for boot menu](http://www.gnu.org/software/grub/manual/grub/grub.html#Boot-Menu)). That file is autogenerated.

Here is a typical Windows menu entry from `/boot/grub/grub.cfg`:

```
menuentry 'Windows Boot Manager (on /dev/sdb1)' --class windows --class os [...]
```

See that `--class windows`? That means that GRUB would look for `windows.png` in theme's `icons` directory, and use it. If it has some different `class` or no `class` at all, GRUB might not have an icon for it.

So, could you please show `grep -i windows /boot/grub/grub.cfg` output?

**Comment by dillasyx** [comment]
My Windows Entry part is:

`menuentry "Windows 10" {`
`insmod part_gpt`
`insmod fat`
`insmod chain`
`search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt1 -- hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1 XXXX-XXXX`
`chainloder /EFI/Microsoft/Boot/bootmgfw.efi`
`}`

As explained in the Arch Wiki, so yeah there is no --class as you mentioned above. I will try to add --class windows right after the name. Thanks for the fast reply.
