### ISSUE TITLE
Fix grub update path for for Fedora

### ISSUE THREAD

**Issue by ShawonAshraf** [shvchk/fallout-grub-theme#23]
Since Fedora34, the default grub update path for grub has changed, [as mentioned here](https://fedoraproject.org/wiki/GRUB_2#Updating_the_GRUB_configuration_file). Hence,

`GRUB_CFG='/boot/grub2/grub.cfg'` should be updated to GRUB_CFG='/etc/grub2.cfg'. 

Similarly, other vars related to this should be updated as well. Otherwise the users will end up with a broken bootloader :)

**Comment by shvchk** [comment]
Should be fixed now, see [e843386](https://github.com/shvchk/fallout-grub-theme/commit/e8433860b11abb08720d7c32f5b9a2a534011bca)
