### ISSUE TITLE
Fallout Theme Not Loaded

### ISSUE THREAD

**Issue by GetRektBoy724** [shvchk/fallout-grub-theme#8]
I Install with install.sh script
after i run it there is no problem
but i see something strange with update-grub command
this my update-grub command output : 
----------------------------------------------------------------------------------------------
root@GetRektBoy724:~# update-grub
Generating grub configuration file ...
Found theme: /boot/grub/themes/kali/theme.txt
Found background image: /usr/share/images/desktop-base/desktop-grub.png
Found linux image: /boot/vmlinuz-5.8.0-kali2-amd64
Found initrd image: /boot/initrd.img-5.8.0-kali2-amd64
Found linux image: /boot/vmlinuz-5.7.0-kali1-amd64
Found initrd image: /boot/initrd.img-5.7.0-kali1-amd64
Found Windows Boot Manager on /dev/sda1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for EFI firmware configuration
done
----------------------------------------------------------------------------------------------
i never modify my grub
i running kali linux 2020.3

**Comment by GetRektBoy724** [comment]
PLS HELLPPP

**Comment by sathvik139** [comment]
Yes I was tying to change it to but I was not able to chang the grub theme

**Comment by sathvik139** [comment]
Yes I was also trying to change it in kali 2020.3 but I am unable to change it.
